#------------------------------------------------------------------------------
# Makefile
# Programmer: Tiancheng Fu
# CMPS 12B
# Date: July 6th, 2018
# Cruzis: tfu6
# This is a Writefile for Recursion.java
# A Makefile with macros
#------------------------------------------------------------------------------

JAVASRC = Recursion.java
SOURCES = README Makefile $(JAVASRC)
MAINCLASS = Recursion
CLASSES = Recursion.class
JARFILE = Recursion
SUBMIT = submit cmps012b-pt.u18 pa1

all: $(JARFILE)

$(JARFILE): $(CLASSES)
	echo Main-class: $(MAINCLASS) > Manifest
	jar cvfm $(JARFILE) Manifest $(CLASSES)
	rm Manifest
	chmod +x $(JARFILE)
$(CLASSES): $(JAVASRC)
	javac -Xlint $(JAVASRC)

clean:
	rm $(CLASSES) $(JARFILE)

submit: $(SOURCES)
	$(SUBMIT) $(SOURCES)

check:

	ls /afs/cats.ucsc.edu/class/cmps012b-pt.u18/pa1/tfu6
