#------------------------------------------------------------------------------
# Makefile for CMPS 12M Lab Assignment 6
# Programmer: Tiancheng Fu
# CMPS 12M
# Date: August 10th, 2018
# Cruzid: tfu6
# This is a Makefile for java files in Lab 6
#------------------------------------------------------------------------------

# Variables
JARFILE    = ListClient
MAINCLASS  = ListClient
SOURCES    = List.java ListInterface.java ListClient.java\
             ListIndexOutOfBoundsException.java
CLASSES    = List.class ListInterface.class ListClient.class List\$$Node.class\
             ListIndexOutOfBoundsException.class

# Build Targets
all: $(JARFILE)

$(JARFILE): $(CLASSES)
	echo Main-class: $(MAINCLASS) > Manifest
	jar cvfm $(JARFILE) Manifest $(CLASSES)
	rm Manifest
	chmod +x $(JARFILE)

$(CLASSES): $(SOURCES)
	javac -Xlint $(SOURCES)

clean:
	rm -f $(CLASSES) $(JARFILE)

check:

	ls /afs/cats.ucsc.edu/class/cmps012b-pt.u18/lab6/tfu6